### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by diamondflush** [DreamingRaven/dreamingraven#2]
After days of trying to dockerize the nvchad nvim setup, I found this...  

https://githubmemory.com/repo/wbthomason/packer.nvim/issues/599

Thank you so much for the silent packer sync :)

**Comment by DreamingRaven** [comment]
no problem, i'm glad my snippet helped you out from when I was trying to create [this](https://gitlab.com/deepcypher/dockeride), I had hoped to save others the absolute misery it was to find this out! Glad it helped and i'm sorry it didn't reach you sooner!
